---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: sha256sum-web
  name: sha256sum-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sha256sum-web
  template:
    metadata:
      labels:
        app: sha256sum-web
    spec:
      containers:
      - name: sha256sum-web
        image: mailtruck/sha256sum-web:latest
        ports:
        - name: sha256sum-web
          containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: sha256sum-web
spec:
  ports:
  - name: sha256sum-web
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: sha256sum-web